config/routes.rb
Rails.application.routes.draw do
  
  get 'profiles/index'

  resources :likes, only: [:create, :destroy]
  resources :comments

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:show]


  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"

  get 'posts/myposts'
  resources :posts
 root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord

  
  validates :title, presence: true, length: { minimum: 1, maximum: 100}
  validates :description, presence: true, length: { minimum: 1, maximum: 500}
  validates :keywords, presence: true, length: { minimum: 1, maximum: 100}

  has_many_attached :images

  belongs_to :user

  has_many :comments

has_many :likes

  before_create :randomize_id
  private
  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000_000)
    end while User.where(id: self.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
include Pagy::Backend

  def index
    @posts = Post.order(:created_at => :desc)
    @pagy, @posts = pagy_countless(@posts, items: 1)
  end

  def show
    @comment = @post.comments.build
   end

  def myposts
    @posts = Post.all
  end
  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keywords, :user_id, images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  include Pagy::Frontend
end

app/views/posts/_form.html.erb
<div class="container">
  <%= form_with(model: post) do |form| %>
    <h1>New post</h1>
    <div>
      <% invalid = post.errors.include?(:title)%>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:title).join(" ,")%>
        </p>
      <% end %>
    </div>
    <div>
      <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
    </div>
    <div>
      <% invalid = post.errors.include?(:description)%>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:description).join(" ,")%>
        </p>
      <% end %>
    </div>
    <div>
      <% invalid = post.errors.include?(:keywords)%>
      <%= form.label :keywords, style: "display: block" %>
      <%= form.text_field :keywords, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:keywords).join(" ,")%>
        </p>
      <% end %>
      <%= form.file_field :images, multiple:true %>
    </div>
    <div>
      <%= form.submit class:"btn btn-primary col-12" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="instagram-card">
    <div class="instagram-card-header">
      <%= image_tag(post.user.avatar, class:"instagram-card-user-image") %>
      <a class="instagram-card-user-name" href= <%= post.user %> >
        <%= post.user.username %>
      </a>
      <div class="instagram-card-time">
        <%= time_ago_in_words(post.created_at)  %>
      </div>
    </div>
  
    <div class="intagram-card-image">
      <% post.images.each do |image| %>
        <%= image_tag(image, style: "width:100%;") %>
      <% end %>    
  </div>
  
    <div class="instagram-card-content">
      <p class="likes">
        <% if user_signed_in? %>
          <% like = current_user.likes.find_by(post: post) %>
          <% if like.nil? %>
            <%= button_to "like", likes_path, params: { like: { post_id: post.id }}, method: :post%>
          <% else %>
            <%= button_to "Unlike", like_path(like), method: :delete %>
          <% end %>
        <% end %>
        <%= post.likes.count %> Likes</p>
      <p>
        <a class="instagram-card-content-user" href=<%= post.user %> >
          <%= post.user.username %>
        </a>
        <strong> <%= post.title %></strong>
        <br>
        <%= post.description %>
       </p>

      <% @comment = post.comments.build %>

      <p class="comments"> <%= post.comments.count %>  comments</p>
     
      <%= render "comments/form", comment: @comment%>

        <% post.comments.each do |comment|%>
        
          <%= comment.text%>
          <br>
        <% end %>
    <hr>
    </div>
  </div>

  <br>

app/views/posts/discover.html.erb
<% @posts.each do |post| %>
  <%= render post %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag :results, data: { turbo_action: 'advance' } do %>
  <div id="posts"></div>
  <%= turbo_frame_tag :pagination, loading: :lazy,
                      src: posts_path(format: :turbo_stream) %>
<% end %>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append :posts do %>
  <% @posts.each do |post| %>
    <% if user_signed_in? %>
      <% if current_user.following?(post.user) %>
        <%= render post %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<% if @pagy.next.present? %>
  <%= turbo_stream.replace :pagination do %>
    <%= turbo_frame_tag :pagination, loading: :lazy,
                        src: posts_path(format: :turbo_stream, page: @pagy.next) %>
  <% end %>
<% end %>

app/views/posts/myposts.html.erb
<p style="color: green"><%= notice %></p>
<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <% if post.user.id == current_user.id %>
      <%= render post %>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row"><%= render "form", post: @post %>
</div>
<br>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @post %>
<%= link_to "Back to posts", posts_path %>
<% if user_signed_in? %>
  <% if current_user.id == @post.user.id %>
    <div>
      <%= link_to "Edit this post", edit_post_path(@post) %> |
      <%= button_to "Destroy this post", @post, method: :delete %>
    </div>
  <% end %>
<% end %>

app/views/posts/users.html.erb
  
<div id="posts" class="text-center">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>